# if disabled, will not generate file previews for uploaded files
[RabbitMq]
# required
enabled = true
# required if RabbitMq.enabled = true
address = "amqp://127.0.0.1:5672"

# Queue Jobs (file previews, EXIF processing, etc) REQUIRE ffmpeg to run
[QueueJobs]
# the number of milliseconds to wait after a request before queue jobs will be processed. This is on a per-item basis
sleepTimeMillis = 30_000

[Database]
location = "./db.sqlite"
